### ISSUE TITLE
Add PrometheusRule object

### ISSUE THREAD

**Issue by lukas-vlcek** [openshift/elasticsearch-operator#20]
We need to provide `PrometheusRule` object holding the file with alerting (and recording) rules.

Basic resource:

- The starting documentation can be found here: [prometheus-operator/Alerting](https://github.com/coreos/prometheus-operator/blob/master/Documentation/user-guides/alerting.md) and check CR example with:
```
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
...
```
- Other resources can be found all around the source code - [search prometheus-operator repo for PrometheusRule](https://github.com/coreos/prometheus-operator/search?q=PrometheusRule&unscoped_q=PrometheusRule).

- It seems to me the whole build is initiated from within [`make`](https://github.com/coreos/prometheus-operator/blob/master/Makefile) which generates the prometheus rules files and these are then used in [contrib/kube-prometheus/jsonnet/kube-prometheus/prometheus/prometheus.libsonnet](https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/jsonnet/kube-prometheus/prometheus/prometheus.libsonnet#L43-L58)

- We are currently developing Prometheus rules and alerts here: https://github.com/lukas-vlcek/elasticsearch-mixin

//cc @brancz

**Comment by lukas-vlcek** [comment]
@brancz Looking at the following example:

```yaml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  labels:
    prometheus: example
    role: alert-rules
  name: prometheus-example-rules
spec:
  groups:
  - name: ./example.rules
    rules:
    - alert: ExampleAlert
      expr: vector(1)
```
It also reads:

> The best practice is to label the PrometheusRules containing rule files with role: alert-rules as well as the name of the Prometheus object, prometheus: example in this case.

How or where should I get the name of Prometheus object to go with? In this example it refers to `example`. Does the Prometheus running inside the `openshift-monitoring` component has any cluster-wide standardized name then?

**Comment by brancz** [comment]
We won't be selecting Rule objects based on labels, so you can label it as you see fit, or just skip them :slightly_smiling_face:.

**Comment by lukas-vlcek** [comment]
@brancz Then all that needs to be done are two following two things:

### 1) Generate ./elasticsearch-logging.rules file
This will be initiated from the Dockerfile and pull sources from Elasticsearch mixin (wherever it will be located at).

### 2) Create CR like to following one:
```yaml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  name: prometheus-example-rules
spec:
  groups:
  - name: ./elasticsearch-logging.rules
```
Done (maybe?)

**Comment by lukas-vlcek** [comment]
After discussing this more with @brancz and @sichvoge on Slack we should move this into [openshift/cluster-logging-operator](https://github.com/openshift/cluster-logging-operator). Then this will be modelled similar to how **cluster-monitoring-operator** and **prometheus-operator** are made.
//cc @ewolinetz 

### 1) Generate Elasticsearch Promethues rules file

We should keep Elasticsearch mixin separate for now. It will allow use to use tags on the repo for proper release process.

To generate Elasticsearch Prometheus alerts and rules [follow this guide](https://github.com/lukas-vlcek/elasticsearch-mixin#quick-and-dirty-hint).

### 2) Create and manage PrometheusRule CR from cluster-logging-operator

We need to create object like:
```
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  name: openshift-logging-prometheus-rules
spec:
  groups: <content of the rule and alert files (*)>
```
_(*) See [here](https://github.com/coreos/prometheus-operator/blob/82a6ad2071ff653e38b3b4719ecb789d73f3ab05/contrib/kube-prometheus/jsonnet/kube-prometheus/prometheus/prometheus.libsonnet#L43-L58) for example how this is done in prometheus-operator._
