### ISSUE TITLE
failed to create or get service for metrics

### ISSUE THREAD

**Issue by faust64** [openshift/elasticsearch-operator#205]
Starting the ElasticSearch operator on OpenShift, we would find the following warning:

```
# oc logs -f elasticsearch-operator-5d4b85bcf8-65cb9
...
{"level":"info","ts":1574348719.3720665,"logger":"kubebuilder.controller","msg":"Starting EventSource","controller":"elasticsearch-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1574348719.5793352,"logger":"cmd","msg":"failed to create or get service for metrics: services \"elasticsearch-operator\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>"}
...
```

Looks like a warning, though could be worth fixing. Couldn't figure out what's wrong: I don't have an `elasticsearch-operator` service yet. Tried to create it, with then without an `ownerReference` to my operator deployment.

Source image for the ElasticSearch operator pod: registry.redhat.io/openshift4/ose-elasticsearch-operator@sha256:69968bc98d29773b89ba9b3c3c5b1fc44d8df5226934683e3029ae14f4829fab

**Comment by matancarmeli7** [comment]
hi, i get it too, there is a way that i can handle this problem for now?

**Comment by jcantrill** [comment]
> Starting the ElasticSearch operator on OpenShift, we would find the following warning:
> 
> ```
> # oc logs -f elasticsearch-operator-5d4b85bcf8-65cb9
> ...
> {"level":"info","ts":1574348719.3720665,"logger":"kubebuilder.controller","msg":"Starting EventSource","controller":"elasticsearch-controller","source":"kind source: /, Kind="}
> {"level":"info","ts":1574348719.5793352,"logger":"cmd","msg":"failed to create or get service for metrics: services \"elasticsearch-operator\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>"}
> ...
> ```
> 
> Looks like a warning, though could be worth fixing. Couldn't figure out what's wrong: I don't have an `elasticsearch-operator` service yet. Tried to create it, with then without an `ownerReference` to my operator deployment.
> 
> Source image for the ElasticSearch operator pod: registry.redhat.io/openshift4/ose-elasticsearch-operator@sha256:69968bc98d29773b89ba9b3c3c5b1fc44d8df5226934683e3029ae14f4829fab

How did you deploy the operator?

**Comment by faust64** [comment]
Using OCP (4.2) OperatorHub, following instructions deploying OCP logging stack -- https://docs.openshift.com/container-platform/4.2/logging/cluster-logging-deploying.html.

From the notes I took back then, having installed the operator from the OperatorHub console, I then created the following:

```
---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-logging
  annotations:
    openshift.io/node-selector: ""
  labels:
    openshift.io/cluster-logging: "true"
    openshift.io/cluster-monitoring: "true"
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cluster-logging
  namespace: openshift-logging
spec:
  channel: "4.2"
  installPlanApproval: Automatic
  name: cluster-logging
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: clusterlogging.4.2.0-201910101614
---
apiVersion: logging.openshift.io/v1
kind: ClusterLogging
metadata:
  name: instance
  namespace: openshift-logging
spec:
  managementState: Managed
  logStore:
    type: elasticsearch
    elasticsearch:
      resources:
        limits:
          memory: 16Gi
        requests:
          cpu: 1200m
          memory: 16Gi
      nodeCount: 1
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      storage:
        storageClassName: ceph-storage
        size: 200Gi
      redundancyPolicy: ZeroRedundancy
  visualization:
    type: kibana
    kibana:
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      replicas: 2
  curation:
    type: curator
    curator:
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      schedule: "30 3 * * *"
  collection:
    logs:
      type: fluentd
      fluentd: {}
```
