### ISSUE TITLE
certificates error with default config

### ISSUE THREAD

**Issue by ryandawsonuk** [openshift/elasticsearch-operator#323]
I'm running openshift 4.3.9 and have installed the elasitcsearch operator through the embedded OperatorHub UI. When I go through the operator page under 'Installed Operators' in OpenShift, I have the option to create an Elasticsearch instance and it gives me a default configuration:
```
apiVersion: logging.openshift.io/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: openshift-operators
spec:
  managementState: Managed
  nodeSpec:
    image: >-
      registry.redhat.io/openshift4/ose-logging-elasticsearch5@sha256:d2047214be2e9c809440803ccf5972d99e72db3172f110e4be3d4b87550b9902
    resources:
      limits:
        memory: 1Gi
      requests:
        memory: 512Mi
  redundancyPolicy: SingleRedundancy
  nodes:
    - nodeCount: 1
      roles:
        - client
        - data
        - master
```

I had to change SingleRedundancy to ZeroRedundancy as with just one node it resulted in an error in the operator saying SingleRedundancy was invalid. After that change it created an elastic but the Pod gets stuck in ContainerCreating due to a Certificate problem:
```
  Warning  FailedMount  10m (x3 over 31m)     kubelet, ip-10-0-168-54.eu-west-3.compute.internal  Unable to attach or mount volumes: unmounted volumes=[certificates], unattached volumes=[elasticsearch-metrics elasticsearch-storage elasticsearch-config certificates elasticsearch-token-6vssr]: timed out waiting for the condition
  Warning  FailedMount  2m39s (x23 over 33m)  kubelet, ip-10-0-168-54.eu-west-3.compute.internal  MountVolume.SetUp failed for volume "certificates" : secret "elasticsearch" not found
```
