### ISSUE TITLE
Running elasticsearch on CRC

### ISSUE THREAD

**Issue by huikang** [openshift/elasticsearch-operator#527]
Hi, I am having an issue of bringing up elasticsearch on an CRC cluster with the operator. The es instance is configured to have 2G memory. However, the container keeps failing due to ``[1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]``

- CRC version

```
CodeReady Containers version: 1.17.0+99f5c87
OpenShift version: 4.5.14 (embedded in binary)
```

The pod description shows
```
    Limits:
      memory:  2Gi
    Requests:
      cpu:      100m
      memory:   2Gi
    Readiness:  exec [/usr/share/elasticsearch/probe/readiness.sh] delay=10s timeout=30s period=5s #success=1 #failure=3
    Limits:
      memory:  64Mi
    Requests:
      cpu:     100m
      memory:  64Mi
Collapse
```

It looks to me that the setting of 2Gi should overwrite the default 64M. But why the container still failed? Thanks.

**Comment by ewolinetz** [comment]
@huikang this is specifically talking about the node's `vm.max_map_count` setting. There is normally an operator that updates this setting, I'm not sure if running this on CRC is different, I would need to defer to someone who has stood up a cluster on CRC in the past.

@vimalk78 @syedriko @periklis ?

**Comment by syedriko** [comment]
@huikang For future issues, could you describe your environment and the steps that led to the issue you're reporting?

I repro'd what you're reporting on
```
[localhost crc-linux-1.17.0-amd64]$ ./crc version
CodeReady Containers version: 1.17.0+99f5c87
OpenShift version: 4.5.14 (embedded in binary)
[localhost crc-linux-1.17.0-amd64]$
```
with
```
apiVersion: "logging.openshift.io/v1"
kind: "ClusterLogging"
metadata:
  name: "instance"
  namespace: "openshift-logging"
spec:
  managementState: "Managed"
  logStore:
    type: "elasticsearch"
    elasticsearch:
      nodeCount: 1
      storage: {}
      redundancyPolicy: "ZeroRedundancy"
      resources:
        requests:
          cpu: "100m"
          memory: "2Gi"
...
```
The fix for now is
```
[localhost crc]$ oc get nodes
NAME                 STATUS   ROLES           AGE   VERSION
crc-j55b9-master-0   Ready    master,worker   8d    v1.18.3+970c1b3
[localhost crc]$ oc debug node/crc-j55b9-master-0
Starting pod/crc-j55b9-master-0-debug ...
To use host binaries, run `chroot /host`
Pod IP: 192.168.126.11
If you don't see a command prompt, try pressing enter.
sh-4.2# chroot /host
sh-4.4# echo "vm.max_map_count=262144" >> /etc/sysctl.conf
sh-4.4# sysctl -w vm.max_map_count=262144
vm.max_map_count = 262144
sh-4.4# exit
exit
sh-4.2# exit
exit

Removing debug pod ...
[localhost crc]$ 
```
You'll need to reapply it every time you recreate the CRC VM.

As far as I recall, this used to be broken, then got fixed and now seems to have regressed.
