### ISSUE TITLE
Unable to launch a  Kibana CR instance using latest ElasticSearch operator, Steps needed

### ISSUE THREAD

**Issue by Abu0108** [openshift/elasticsearch-operator#557]
**Describe the bug**
Unable to launch a  Kibana CR instance using latest ElasticSearch operator

**Environment**
- OCP 4.5 

**Logs**
We don't see any Error messages neither any resources created.

**Expected behavior**
Kibana CR instance created successfully and connected to Elastic instance and able to login via route

**Actual behavior**
Nothing happens, no pods, no secrets get created.

**To Reproduce**
1. Install ElasticSearch Operator in <xyz> namespace
2. Create a ElasticSearch CR instance and then Kibana CR instance using the default CR 
3. ElasticSearch pods get launched, but KIbana pods dont get launched.
4. No Error or anything to debug

**Additional context**
YAML File of Kibana CR instance:

```
apiVersion: logging.openshift.io/v1
kind: Kibana
metadata:
  name: kibana
  namespace: xyz
spec:
  replicas: 1
  resources:
    limits:
      memory: 512Mi
    requests:
      memory: 512Mi
  managementState: Managed
  nodeSelector: {}
```

**Comment by huikang** [comment]
Could you paste the log from the elasticsearch-operator? Thanks.

**Comment by Abu0108** [comment]
hello, thanks for ur response. we dont see any elastic-search operator pod in this **xyz** namespace
Rather there is one in the **openshift-operators-redhat** namespace

**Comment by Abu0108** [comment]
Below is ElasticInstance:

```
apiVersion: logging.openshift.io/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: xyz
spec:
  managementState: Managed
  nodeSpec:
    image: >-
      registry.redhat.io/openshift4/ose-logging-elasticsearch6@sha256:2c156f7e8896011e7eac8c58e661d3173ff8079d0b3f16045b1ac9cc68f4496f
    resources:
      limits:
        memory: 1Gi
      requests:
        memory: 512Mi
  nodes:
    - nodeCount: 1
      roles:
        - client
        - data
        - master
  redundancyPolicy: ZeroRedundancy
```

**Comment by Abu0108** [comment]
Is there any example or steps documented that can be referred to create ElasticInstance and Kibana CR instances, as I suspect we could be missing something

**Comment by huikang** [comment]
> hello, thanks for ur response. we dont see any elastic-search operator pod in this **xyz** namespace
> Rather there is one in the **openshift-operators-redhat** namespace

Yes, this is one I am referring to.

- The example you used only launches the elasticsearch instance, which is the expected. For kibana, the example is located at: https://github.com/openshift/elasticsearch-operator/blob/5dd0f4fc56ecc259a5f8c30074570e33df1d3c28/test/e2e-olm/utils.go#L263

**Comment by ewolinetz** [comment]
@Abu0108 do you have the cluster logging operator installed as well? we recommend using that if you are going to be deploying elasticsearch for logging

**Comment by abu-2020-ghub** [comment]
> > hello, thanks for ur response. we dont see any elastic-search operator pod in this **xyz** namespace
> > Rather there is one in the **openshift-operators-redhat** namespace
> 
> Yes, this is one I am referring to.
> 
> * The example you used only launches the elasticsearch instance, which is the expected. For kibana, the example is located at: https://github.com/openshift/elasticsearch-operator/blob/5dd0f4fc56ecc259a5f8c30074570e33df1d3c28/test/e2e-olm/utils.go#L263

Thanks.. We did try launching Kibana Instance separately but we dont see anything happening.
No resources created at all.

```
apiVersion: logging.openshift.io/v1
kind: Kibana
metadata:
  name: kibana
  namespace: xyz
spec:
  replicas: 1
  resources:
    limits:
      memory: 512Mi
    requests:
      memory: 512Mi
  managementState: Managed
  nodeSelector: {}
```

![image](https://user-images.githubusercontent.com/68229655/97838022-5b601e80-1d05-11eb-8b59-d743843ecfe7.png)

![image](https://user-images.githubusercontent.com/68229655/97838049-6b77fe00-1d05-11eb-832c-e09bde73bd14.png)

![image](https://user-images.githubusercontent.com/68229655/97838078-7af74700-1d05-11eb-9cf0-77b602618776.png)
