### ISSUE TITLE
Index creation permission

### ISSUE THREAD

**Issue by jstakun** [openshift/elasticsearch-operator#611]
Hello

I'm trying to integrate Elastalert with OCP 4.5 Cluster Logging. This requires permission to get/create indexes. I've created SA with cluster-admin role but I'm still not allowed to access indexes:

[2021-01-07T14:54:21,035][INFO ][c.a.o.s.p.PrivilegesEvaluator] [elasticsearch-cdm-luzbzv0n-1] No index-level perm match for User [name=system:serviceaccount:openshift-elastalert:elastalert, roles=[admin_reader], requestedTenant=null] Resolved [aliases=[], indices=[elastalert_status], allIndices=[elastalert_status], types=[*], originalRequested=[elastalert_status], remoteIndices=[]] [Action [indices:admin/get]] [RolesChecked [admin_user]]
[2021-01-07T14:54:21,035][INFO ][c.a.o.s.p.PrivilegesEvaluator] [elasticsearch-cdm-luzbzv0n-1] No permissions for [indices:admin/get]

Please advice how and what permission should I grant.

**Comment by jstakun** [comment]
I made some progress. In ES pods I've manually edited roles_mapping.yaml add added my user to sg_role_admin followed by calling es_seed_acl.
This seems to work only with users and not service accounts? (I'd prefer to use SA long lived tokens and instead of users short lived tokens)
Is there any way to make this modification persistent way using operator configuration?

**Comment by jstakun** [comment]
Any plans to allow ES roles configuration from operator CRD?

**Comment by akilada** [comment]
We have been using Elastalert with OCP ES 4.4. After upgrading CLO and ES operators to 4.6, we couldn't use the logging admin user with the elastalert. 

We have tried the workaround found by @jstakun but it's not a permanent solution. It'll be better if we have given the option to add additional admin users to 'sg_role_admin'.

For example - the ES operation creates an 'elasticsearch' configmap. It has a separate section define admin users. But we can't define another admin user in the cluster logging instance.

`$ oc get cm elastisearch -n openshift-logging -o yaml`

```
...
opendistro_security:
  authcz.admin_dn:
  - CN=system.admin,OU=OpenShift,O=Logging
  config_index_name: ".security"
  restapi:
    roles_enabled: ["kibana_server"]
  ssl:
    transport:
      enabled: true
      enforce_hostname_verification: false
      keystore_type: JKS
      keystore_filepath: /etc/elasticsearch/secret/searchguard.key
      keystore_password: kspass
      truststore_type: JKS
      truststore_filepath: /etc/elasticsearch/secret/searchguard.truststore
      truststore_password: tspass
....
```
