### ISSUE TITLE
How to install from the command line

### ISSUE THREAD

**Issue by software-engr-full-stack** [openshift/elasticsearch-operator#988]
Sorry if this is a basic question but I haven't found the solution after searching online.

How do I install this operator from the command line?

I can install a service mesh operator using `kubectl apply -f` using this file:
```
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: servicemeshoperator
  namespace: openshift-operators
spec:
  channel: stable
  name: servicemeshoperator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
```

But it doesn't work with this operator (after replacing the relevant fields like "name" and "source". By "it doesn't work" I mean when I look up the "Installed Operators" page under "Operators" in the OpenShift web UI (Admin mode), the status is not "Succeeded" like the other operators that were installed successfully.

Thanks in advance.

**Comment by anpingli** [comment]
You should deploy elasticsearch-operator under openshift-operators-redhat namespace. 
1) Create namespace openshift-operators-redhat 
2) Create operatorgroup
```
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-operators-redhat
  namespace: openshift-operators-redhat
  spec: {}
```

3. subscribe to catalogsource
```
{
  "apiVersion": "operators.coreos.com/v1alpha1",
  "kind": "Subscription",
  "metadata": {
    "name": "elasticsearch-operator"
  },
  "spec": {
    "channel": "stable",
    "installPlanApproval": "Automatic",
    "name": "elasticsearch-operator",
    "source": "redhat-operators",
    "sourceNamespace": "openshift-marketplace"
  }
}
```
